

spring.application.name=hei-diplomas

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


spring.jpa.open-in-view=true




spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

spring.jackson.time-zone=Indian/Antananarivo

logging.level.root=INFO
logging.level.school.hei.diplomas=DEBUG